### ISSUE TITLE
[IMPORT ERROR : ChatCompletionRequest]

### ISSUE THREAD

**Issue by ashishakkumar** [mistralai/mistral-common#24]
### Python -VV

```shell
NOT REQUIRED
```

### Pip Freeze

```shell
NOT REQUIRED
```

### Reproduction Steps

NOT REQUIRED

### Expected Behavior

As per the [documentation](https://docs.mistral.ai/guides/tokenization/#run-our-tokenizer-in-python),

**Comment by ashishakkumar** [comment]
Please change _from mistral_common.tokens.instruct.normalize import ChatCompletionRequest_
to  _from mistral_common.protocol.instruct.request import ChatCompletionRequest_

**Comment by pandora-s-git** [comment]
Hi @ashishakkumar , could you tell us where exactly you see this import? As the documentation has been fixed some time ago.

**Comment by ashishakkumar** [comment]
@pandora-s-git 

Yes now it's fixed : https://docs.mistral.ai/guides/tokenization/#run-our-tokenizer-in-python

<img width="865" alt="Screenshot 2024-07-08 at 1 42 24 PM" src="https://github.com/mistralai/mistral-common/assets/86063242/838e0fde-71cd-476e-ab3a-aff5379273a5">
