### ISSUE TITLE
[release] need a new version in pip install to work with python 3.12

### ISSUE THREAD

**Issue by zffocussss** [mistralai/mistral-common#25]
### Python -VV

```shell
3.12
```

### Pip Freeze

```shell
1.2.1
```

### Reproduction Steps

1.   create a docker image in debian bullseye with python 3.12
2.  pip install mistral-common==1.2.1

### Expected Behavior

pip install mistral-common can work in python 3.12

### Additional Context

![Xnip2024-07-09_10-37-09](https://github.com/mistralai/mistral-common/assets/46145695/ef1297bd-125a-4c69-be60-55d5ea0fd7e4)

### Suggested Solutions

the main branch updated sentencepiece already.the team can release a new version in pypi only based on the main branch,for example 1.2.2

**Comment by anetbnd** [comment]
Yes please make a new release, to push sentencepiece to 0.2.0, I have the same issue.

**Comment by patrickvonplaten** [comment]
Should be done in 1.3.1 :-)

**Comment by anetbnd** [comment]
Thanks
